version: 2
jobs:

  create_docker_image:

    docker:
      - image: docker:18.09

    environment:
      QUAY_ENDPOINT: "quay.io"
      QUAY_ORG: "jeroenmanders"
      IMAGE: "quay.io/jeroenmanders/infraxys-upgrader"

    working_directory: /build

    steps:
      - checkout:
          path: /build

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Docker login
          command: |
            echo "Logging into quay with $quay_username.";
            echo "$quay_token" | docker login -u="${quay_username}" quay.io --password-stdin;

      - run:
          name: Install prerequisites
          command: |
            apk --no-cache add curl;

      - run:
          name: Docker build and push full version
          command: |
            export FULL_VERSION="$(cat VERSION)_${CIRCLE_SHA1}_${CIRCLE_BUILD_NUM}"
            ./build.sh "$FULL_VERSION";

            #echo "Pushing ${IMAGE}:${FULL_VERSION}.";
            #docker push ${IMAGE}:${FULL_VERSION};

      - run:
          name: Docker push release and latest for master only
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export FULL_VERSION="$(cat VERSION)_${CIRCLE_SHA1}_${CIRCLE_BUILD_NUM}";
              export RELEASE_VERSION="$(cat VERSION)";
              docker tag ${IMAGE}:${FULL_VERSION} ${IMAGE}:${RELEASE_VERSION};
              docker tag ${IMAGE}:${FULL_VERSION} ${IMAGE}:latest;
              echo "This is master. Pushing version ${RELEASE_VERSION} and latest.";
              docker push ${IMAGE}:${RELEASE_VERSION};
              docker push ${IMAGE}:latest;
            fi;


workflows:
  version: 2
  build:
    jobs:
      - create_docker_image:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - master
          context: vars

